#language: node_js
#node_js:
#  - "8.3"
sudo: required
services:
  - docker
env:
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_TARGET=coverage
before_install:
  - docker pull node:8-onbuild
install:
  - docker build -t probot-hello .
script:
  - docker run -it --rm probot-hello npm run $NPM_TARGET
#  - docker run -it --rm probot-hello npm run lint
after_success:
  - set -x -v;
    set -e;
    if [ "${NPM_TARGET}" = "test"]; then
     docker tag probot-hello probot-hello:$(git rev-parse HEAD)
    else
      echo "skipping docker tag"
