#language: node_js
#node_js:
#  - "8.3"
sudo: required
services:
  - docker
before_install:
  - docker pull node:8-build
install:
  - docker build -t probot-hello .
script:
  - docker run -it --rm probot-hello npm run test
  - docker run -it --rm probot-hello npm run link
after_success:
  - docker tag probot-hello probot-hello:$(git rev-parse HEAD)
